### ISSUE TITLE
Lonely PSUs

### ISSUE THREAD

**Issue by krosenfeld-IDM** [samplics-org/samplics#49]
**Proposed feature**

There are datasets where there is only one PSU in a stratum (e.g., [Nigeria 2013 DHS](https://dhsprogram.com/methodology/survey/survey-display-438.cfm)). In this case the variance cannot be estimated and results in the error:

e.g.,
```
Only one PSU in the following strata: [60]
```

Solutions include "certainty PSUs" or an ad-hoc adjustment (see [this ref](https://r-survey.r-forge.r-project.org/survey/exmample-lonely.html)). Ad-hoc adjustment could be provided as an a new keyword argument to the `TaylorEstimator.estimate` method.

**Comment by MamadouSDiallo** [comment]
Dear @krosenfeld-IDM 

You can try `single_psu` and/or `strata_comb` to see if that resolve your issue.  

```py
def estimate(
        self,
        y: Array,
        samp_weight: Optional[Array] = None,
        x: Optional[Array] = None,
        stratum: Optional[Series] = None,
        psu: Optional[Series] = None,
        ssu: Optional[Series] = None,
        domain: Optional[Series] = None,
        by: Optional[Series] = None,
        fpc: Union[dict[StringNumber, Number], Series, Number] = 1.0,
        deff: bool = False,
        coef_var: bool = False,
        single_psu: Union[SinglePSUEst, dict[StringNumber, SinglePSUEst]] = SinglePSUEst.error,
        strata_comb: Optional[dict[Array, Array]] = None,
        as_factor: bool = False,
        remove_nan: bool = False,
    ) -> None:
```

To use `single_psu`, you will import SinglePSUEst. It is an enum and you can decide to skip the stratum, treat it as a certainty stratum, or combine strata to avoid single psu issue. If you decide to combine, you can use strata_combine to indicate the stata you want to combine. 

Check these tests for examples on how to use the API: [https://github.com/samplics-org/samplics/blob/main/tests/estimation/test_single_psu_strata.py](https://github.com/samplics-org/samplics/blob/main/tests/estimation/test_single_psu_strata.py) 

Note that I have not documented these use cases because I am re-writting the package and the APIs will change significantly. 

With regards

**Comment by krosenfeld-IDM** [comment]
Thank you @MamadouSDiallo - this is a good solution. I'll keep an eye out for the next release.
