### ISSUE TITLE
Documentation details for Sample Size calculation is limited

### ISSUE THREAD

**Issue by mondjef** [samplics-org/samplics#50]
I am trying to work my way through the documentation to figure out how to create a sample that is equally distributed across stratums.  If the sample size is calculated to be 200 and I have 10 stratums I want 20 selected for each stratum.  I have tried to follow the example in the documentation for calculating sample size but I am failing to understand how this is applied to a frame (pandas data frame) or if needs to be...or do I wrangle the data frame myself beforehand to provide things such as pop_size to the SampleSize object?  I tried reading the code and found reference to other methods like 'equal' and 'total' but not sure how to use or reference.  Is there something missing from documentation or could somebody walk me through a bit more?

**Comment by MamadouSDiallo** [comment]
Hi @mondjef 

I am not sure what you need. If the strata have the same specifications then the sample size calculation will produce the same number for all the strata. However, if you have a given sample size that you will allocate equally then it is a allocation issue. In this case, it is very easy since it is the same number. Using a library for equal allocation seems overkill. is this what you trying to do?

Obviously, I did not understand your question. Please clarify what you need maybe with a complete (simplified) use case.

**Comment by MamadouSDiallo** [comment]
Certainly, the documentation is not up to the desired standard at the moment. I'm in the process of redesigning certain APIs, and as a result, I've opted to postpone the documentation for the time being. However, progress is not as swift as I'd prefer it to be. 

I updated the sample size calculation code. It's for a proportion (`PopParam.pop`), stratified, with precision (half confidence interval `half_ci`) of 0.1, etc. The number of strata is 5. But because I did not provide the information by stratum using Python dictionaries, it will consider the information to be the same for all the strata.

```python
from samplics.sampling import SampleSize
from samplics.utils.types import PopParam, SizeMethod

sample_size = SampleSize(param=PopParam.prop, method=SizeMethod.wald, strat=True)
sample_size.calculate(half_ci=0.15, alpha=0.1, target=0.1, pop_size=100000, nb_strata=5)

sample_size.samp_size
```

We get the following sample sizes for the strata

```python
{
 '_stratum_1': 11,
 '_stratum_2': 11,
 '_stratum_3': 11,
 '_stratum_4': 11,
 '_stratum_5': 11
}
```

Generate data for the examples below.

```python
import numpy as np

x_sim = 5*np.random.randn(50)
y_sim = x + np.random.rand(50)*10.45
w_sim = np.random.choice([4,5,10,12,15], 50)
```

In the examples below, I commented out some of the design information. You can use them as needed. 

```python
# Mean 

from samplics.estimation import TaylorEstimator

mean_str = TaylorEstimator(param="mean", alpha=0.1)
mean_str.estimate(
    y=y_sim,
    samp_weight=w_sim,
    # stratum=str_sim,
    # psu=psu_sim,
    remove_nan=True,
)

print(mean_str)
```

```python
# Total 

from samplics.estimation import TaylorEstimator

total_str = TaylorEstimator(param="total", alpha=0.1)
total_str.estimate(
    y=y_sim,
    samp_weight=w_sim,
    # stratum=str_sim,
    # psu=psu_sim,
    remove_nan=True,
)

print(total_str)
```

For the ratio estimator, we need both y and x to estimate `Y/X`

```python
# Ratio 

from samplics.estimation import TaylorEstimator

ratio_str = TaylorEstimator(param="ratio", alpha=0.1)
ratio_str.estimate(
    y=y_sim,
    x=x_sim,
    samp_weight=w_sim,
    # stratum=str_sim,
    # psu=psu_sim,
    remove_nan=True,
)

print(ratio_str)
```

**Comment by mondjef** [comment]
thank you @MamadouSDiallo , I was able to get everything to work using the information you provided and have tested our Python pipeline to that of what we previously had done with SAS and the results are exactly the same or very close (some rounding differences I think).  I will mark this resolved and will certainly promote the library within my organization which may promote assistance with the code base.
